### ISSUE TITLE
tweb in a ready docker image

### ISSUE THREAD

**Issue by vpinigin** [morethanwords/tweb#182]
Is there possible to prepare a docker ready image for dockerhub for others to pull it?

**Comment by kokojacket** [comment]
Support~!  __

**Comment by Koradris** [comment]
Very useful!

**Comment by TanvirOnGH** [comment]
I want this as well.

**Comment by Moustafa-Elgammal** [comment]
Hello community,

I have create docker services, for develop env and also production build, check my PR #332 

I also created an image https://hub.docker.com/r/elgammalx/tweb/tags  based on Nginx ready to be deployed.

You can use `docker build -f ./.docker/Dockerfile_production -t {dockerhub-username}/{imageName}:{latest}` to build your production ready image.

My build use in `docker-compose.yaml` file
```yaml
services:
  tweb.production:
    image: elgammalx/tweb
    ports:
      - 80:80
```
